//
// Created by Artyom on 19.10.2023.
//

#ifndef ALGORITMS_AND_DS_TIME_COMPLEXITY_FUNCTION_FOR_SEARCHES_H
#define ALGORITMS_AND_DS_TIME_COMPLEXITY_FUNCTION_FOR_SEARCHES_H

#endif //ALGORITMS_AND_DS_TIME_COMPLEXITY_FUNCTION_FOR_SEARCHES_H
